# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Composer Ansible role.
#
# The Webarchitects Composer Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Composer Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Composer Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Composer and PHP version checks
  block:

    - name: Check the version of PHP
      ansible.builtin.command: php -v
      check_mode: false
      changed_when: false
      register: composer_php_v

    - name: Set a fact for the version of PHP
      ansible.builtin.set_fact:
        composer_php_version: "{{ (composer_php_v.stdout_lines[0]).split(' ')[1] | regex_replace('-.*$') }}"

    - name: Print the version of PHP installed
      ansible.builtin.debug:
        var: composer_php_version
        verbosity: 1

    - name: Print the version of Composer required
      ansible.builtin.debug:
        var: composer_version
        verbosity: 1

    - name: Check if Composer is installed
      ansible.builtin.stat:
        path: /usr/local/bin/composer
      check_mode: false
      changed_when: false
      register: composer_path

    - name: Check installed Composer version
      block:

        - name: Check the Composer version
          ansible.builtin.command: /usr/local/bin/composer --no-ansi -V -n
          check_mode: false
          changed_when: false
          register: composer_v

        # The version format might be in a couple of forms
        # Composer version 1.10.9 2020-07-16 12:57:00
        # or
        # Composer 2.0.9 2021-01-27 16:09:27
        - name: Set a fact for the installed version of Composer
          ansible.builtin.set_fact:
            composer_installed: "{{ (composer_v.stdout | regex_replace('Composer') | regex_replace('version') | trim ).split(' ')[0] | trim }}"

        - name: Print the installed version of Composer
          ansible.builtin.debug:
            var: composer_installed
            verbosity: 1

      when: composer_path.stat.exists | bool

    - name: Check the latest version of Composer
      block:

        - name: Check the latest version of Composer
          ansible.builtin.uri:
            url: https://github.com/composer/composer/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          register: composer_headers

        - name: Set a fact for the latest version of Composer
          ansible.builtin.set_fact:
            composer_latest: "{{ composer_headers.location | urlsplit('path') | basename }}"

        - name: Print the latest version of Composer
          ansible.builtin.debug:
            var: composer_latest
            verbosity: 1

      when: composer_version == "latest"

    # See https://blog.packagist.com/composer-2-3/
    - name: Check that PHP >= 7.2.5 when the latest Composer or a version greater than or equal to 2.3.0 is to be installed
      ansible.builtin.assert:
        that:
          - composer_php_version is version('7.2.5', '>=')
      when: ( composer_version == "latest" ) or ( composer_version is version('2.3.0', '>=' ) )

    - name: Check that the version of Composer to be installed is < 2.3.0 when PHP <= 7.2.4
      ansible.builtin.assert:
        that:
          - composer_version is version('2.3.0', '<')
      when: composer_php_version is version('7.2.4', '<=')

  tags:
    - composer
...
