---
- name: Install and update Composer
  block:

    - name: Print the version of Composer required
      ansible.builtin.debug:
        var: composer_version
        verbosity: 1

    - name: Check if Composer is installed
      ansible.builtin.command: which composer
      check_mode: false
      changed_when: false
      register: composer_which
      failed_when: composer_which.rc is not regex('0|1')

    - name: Check installed Composer version
      block:

        - name: Check the Composer version
          ansible.builtin.command: composer --no-ansi -V -n
          check_mode: false
          changed_when: false
          register: composer_v

        - name: Set a fact for the installed version of Composer
          ansible.builtin.set_fact:
            composer_installed: "{{ composer_v.stdout.split(' ')[2] | trim }}"

        - name: Print the installed version of Composer
          ansible.builtin.debug:
            var: composer_installed
            verbosity: 1

      when: composer_which.rc == 0

    - name: Check the latest version of Composer
      ansible.builtin.uri:
        url: https://github.com/composer/composer/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      register: composer_headers

    - name: Set a fact for the latest version of Composer
      ansible.builtin.set_fact:
        composer_latest: "{{ composer_headers.location | urlsplit('path') | basename }}"

    - name: Print the latest version of Composer
      ansible.builtin.debug:
        var: composer_latest
        verbosity: 1

    - name: Install Composer
      ansible.builtin.include_tasks: install.yml
      when: ( composer_which.rc == 1 ) or ( composer_version == "latest" and composer_installed != composer_latest ) or ( composer_version != "latest" and composer_installed != composer_version )

  tags:
    - composer
...
