# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Composer Ansible role.
#
# The Webarchitects Composer Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Composer Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Composer Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as composer is false
  ansible.builtin.debug:
    msg: "The composer variable need to be true for the tasks in this role to run."
  when: not composer | bool
  tags:
    - composer

- name: Install and potentially update Composer
  block:

    - name: Packages present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - php-cli
        update-cache: true
        state: present

    - name: Include Composer version checks
      ansible.builtin.include_tasks: checks.yml

    - name: Install Composer
      ansible.builtin.include_tasks: install.yml
      when: >
        ( composer_which.rc == 1 ) or
        ( composer_version == "latest" and composer_installed != composer_latest ) or
        ( composer_version != "latest" and composer_installed != composer_version )

  when: composer | bool
  tags:
    - composer
...
