---
- name: Install and potentially update Composer
  block:

    - name: Include Composer version checks
      ansible.builtin.include_tasks: checks.yml

    - name: Install Composer
      ansible.builtin.include_tasks: install.yml
      when: >
        ( composer_which.rc == 1 ) or
        ( composer_version == "latest" and composer_installed != composer_latest ) or
        ( composer_version != "latest" and composer_installed != composer_version )

  tags:
    - composer
...
